#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Escolar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sisteminha")]
	public partial class testeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFuncionario(Funcionario instance);
    partial void UpdateFuncionario(Funcionario instance);
    partial void DeleteFuncionario(Funcionario instance);
    #endregion
		
		public testeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionario
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFuncionario;
		
		private string _NomeFuncionario;
		
		private string _CargoFuncionario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFuncionarioChanging(int value);
    partial void OnIdFuncionarioChanged();
    partial void OnNomeFuncionarioChanging(string value);
    partial void OnNomeFuncionarioChanged();
    partial void OnCargoFuncionarioChanging(string value);
    partial void OnCargoFuncionarioChanged();
    #endregion
		
		public Funcionario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFuncionario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdFuncionario
		{
			get
			{
				return this._IdFuncionario;
			}
			set
			{
				if ((this._IdFuncionario != value))
				{
					this.OnIdFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._IdFuncionario = value;
					this.SendPropertyChanged("IdFuncionario");
					this.OnIdFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeFuncionario", DbType="VarChar(50)")]
		public string NomeFuncionario
		{
			get
			{
				return this._NomeFuncionario;
			}
			set
			{
				if ((this._NomeFuncionario != value))
				{
					this.OnNomeFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._NomeFuncionario = value;
					this.SendPropertyChanged("NomeFuncionario");
					this.OnNomeFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargoFuncionario", DbType="VarChar(50)")]
		public string CargoFuncionario
		{
			get
			{
				return this._CargoFuncionario;
			}
			set
			{
				if ((this._CargoFuncionario != value))
				{
					this.OnCargoFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._CargoFuncionario = value;
					this.SendPropertyChanged("CargoFuncionario");
					this.OnCargoFuncionarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
